- platform: command_line
  switches:
    #Switch for seccam Motion Detection
    seccam_motion:
      friendly_name: "Detection de mouvement"
      command_on: '/home/homeassistant/.homeassistant/scirpts/gestion_camera.sh on'
      command_off: '/home/homeassistant/.homeassistant/scirpts/gestion_camera.sh off'
      command_state: '/home/homeassistant/.homeassistant/scirpts/gestion_camera.sh state'
      value_template: '{{ value == "1" }}'